Neovici/cosmoz-tabs

.codeclimate.yml, cosmoz-tab.js, cosmoz-tabs.js, test/basic.html
On `iron-items-changed` listen/unlisten to `disabled-changed` and `hidden-changed` and notify changes on the items array.
fixes #19
=> Forward disabled and hidden to paper-tabs

cosmoz-tabs.js, test/basic.html
Hiding or disabling selected tab should change selection to fallback.
Selecting a hidden or disabled tab should change selection to fallback.
Added tests
fixes #27 
At the moment the hash param will also change when selection is set to fallback.
=> selected  hidden or disbled tab should change selection to fallback

cosmoz-tab.js, cosmoz-tabbable-behavior.html, cosmoz-tabs.js
Limit resize notifications to selected tab and check for visible before firing a resize.
fixes #30
=> Limit resize notifications

cosmoz-tabs.js
Depend on `items` on _selectedItemChanged.
Fixes #35
Fixes a issue in 2.x where items are set async from an observer
=> Depend on items on _selectedItemChanged

cosmoz-tabs.js, test/hash.html
fixes https://github.com/Neovici/cosmoz-tabs/issues/38
test for read hash params only once; test for selected updates location hash second time also.
=> Read hash params only once

cosmoz-tabbed-behavior.html
Sometimes we start a transition but for some reason (depending on a lot of things) the transition is not actually run. 
To fix that we add a timeout of 1s and if the transition doesn't finish in that interval we call the transitionend handler manually to cleanup.
Fixes #55
=> Adds timeout to handle transition not being run

cosmoz-tab-card.html, cosmoz-tab.html, cosmoz-tabs.html
This overrides the font-family with paper-font-common-base, which seems to be the common practice to be able to control the font from the outside.
Testing: Connect to cosmoz-frontend, change the font-family in `--paper-font-common-base` for the theme.
Issue is Redmine 20827.
=> 20827 - Setting paper-font-common-base to override font-family

bower.json, cosmoz-tabs.js, test/.eslintrc.json, test/hash-spec.html, test/helpers/upgrade-dom-templates.html, test/index.html
Fixes Neovici/cosmoz-frontend#1047
=> (minor) read location hash only when cosmoz-tabs becomes visible

cosmoz-tabs.js, test/hash-spec.html
read location hash once when cosmoz-tabs is attached and again after it becomes visible
=> (minor) read location hash once when cosmoz-tabs is attached

cosmoz-tabbable-behavior.html, test/sizing.html
@nomego this is related to the forced layouts after tab changes.
The forced layouts are triggered by the `isVisible` checks (which call `offsetWidth`). We cannot do away with the `isVisible` check altogether, because it is the only reliable way to know that the element is actually rendered and visible to the user.
This update moves the resize notification to the animation frame queue, instead of the microtask queue. This should result in smoother renders, even though the layout is still forced.
=> (patch) notifyResize in an animation frame

.github/workflows/workflow.yml, cosmoz-tab.js, cosmoz-tabbed-behavior.js, cosmoz-tabs.js, package-lock.json, wct.conf.json
I needed a way to force the icon to be displayed when the tabs are not in accordion mode.
The plan is to set `<cosmoz-tab icon-style="display:inline">` to force the configured icon to be displayed.
Re https://github.com/Neovici/cosmoz-frontend/pull/1791
Do you think it's OK to have this type of property or should I instead add a boolean property to limit the customization possibilities (`icon-visible`)?
=> Add icon-style property

.codeclimate.yml, .github/karma-problem-matcher.json, .github/workflows/workflow.yml, package-lock.json, package.json
- codeclimate
- eslint-6
- drop .html linting, bower_components
- karma problem matcher
- setup-node
- eslint problem matcher
- v12.x
- drop github-actions-eslint-annotator
Signed-off-by: Patrik Kullman <patrik.kullman@neovici.se>
=> ci: repo upgrades

cosmoz-tab-card.js
Check that the slot does not impact the regular use and that the use of the slot adds content behind the title.
Redmine #23850.
=> fix: adding after-title slot

cosmoz-tab.js, cosmoz-tabs.js
Check that the badge counter is hidden when the value for the badge is 0 and that is shown if it is above 0.
RM:24231.
=> fix: restore hide badge on negative value #24231

cosmoz-tabs.js, test/sizing.test.js
The max-height set on `#pages` in cosmoz-tabs can limit the tabs to a incorrect size when paper-tabs +margin do not have 51px in size. This happens if you zoom out  or if somehow differrent fonts and weights/sizes are used for paper-tabs ...
=> fix: size tabs correctly when paper-tabs has different size

cosmoz-tabs.js
Improves flex behavior and adds a part for #content
=> fix: flex none for paper-tabs

lib/use-tabs.js
In Firefox the `slotchange` fires a bit too soon ...
=> fix(cosmoz-tabs): delays initial setTabs to microtask

lib/use-tabs.js
This was the behaviour in Polymer and there is code that relies on it.
=> fix: initial "selected-changed" event is not fired

cosmoz-tabs.js, lib/use-tabs.js, test/cosmoz-tabs-basic.test.js
The no-resize option/attribute is usefull (sometimes event needed) so that we don't fire the 'resize' event to force `iron-resize` updates.
=> fix: add no-resize option in cosmoz-tabs

lib/use-hash-param.js
Reads hash params in a animation frame to make sure that the render scheduler queue is ready before we request another state update.
=> fix: read params in a animation frame

lib/use-tabs.js, package-lock.json, package.json, test/cosmoz-tabs-basic.test.js, test/cosmoz-tabs-sizing.test.js
There was an attempt to fix `selected` notification in #126 but it was incomplete.
This restores original `cosmoz-tabs` 's `selected` notification.
=> fix: correctly notify `selected`

lib/use-tabs.js, test/cosmoz-tabs-basic.test.js, test/cosmoz-tabs-hash.test.js
`slotchange` fires very fast and if polymer does a lot of updates to `cosmoz-tabs` even `queueMicrotask` (which we added for similar reasons for Firefox) is too fast to cause a re-render.
=> fix: update children from slot in raf

lib/use-tabs.js, lib/utils.js, test/cosmoz-tabs-basic.test.js, test/cosmoz-tabs-slot.test.js
Notify `selected-changed` while keeping the fallback selection behavior.
Fixes #137
=> fix: notify selected-changed

lib/use-tabs.js
iron-location needs to know when it should re-parse the url, otherwise components that use cosmoz-page-location will not track the url properly, leading to lost parameters.
=> fix(use-tabs): iron-location interop

lib/use-tabs.js
Scrolls the tabs only horizontally.
=> fix(use-tabs): scroll only horizontally

lib/use-tabs.js, package-lock.json, package.json
Replaces calls to scrollIntoVIew with the `compute-scroll-into-view`
module with `boundary` support.
=> fix(use-tabs): uses compute-scroll-into-view

src/use-tab.js
I want to make code like this work:
```html
<cosmoz-tab
heading="[[ _('Executive summary', t) ]]"
name="executive-summary"
has-briefs
>
<executive-summary-tab has-cards invoice="[[_invoice]]"></executive-summary-tab>
</cosmoz-tab>
```
`executive-summary-tab` is a component without shadowRoot. It contains `cosmoz-tab-cards` and it has `display: contents`.
=> feat: support for cosmoz-tab-cards nested in other elements

package-lock.json, package.json, src/cosmoz-tab-card.js, src/utils.js, stories/cosmoz-tab-card.stories.js
feature [AB#13618](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/13618) - create a collapsible tab card.
=> feat: collapsing tab card

src/cosmoz-tab-card.js
Wrap content around cosmoz-collapse.
Use `.collapse-icon` class to style the collapse icon.
=> feat(tab-card): adjust collapsable

src/cosmoz-tab-card.js
Fix cosmoz-tab-card sizing by always filling the width.
=> fix(cosmoz-tab-card): fix sizing

.vscode/settings.json, src/cosmoz-tab-card.js
[AB#12608](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/12608) - remake of a [previous PR](https://github.com/Neovici/cosmoz-tabs/pull/198) whose rebase was proving too tricky
=> feat(bg-color): bg color manageable from the outside via css vars

src/render.js
cosmoz-tabs-badge-font-family variable will now fallback to cosmoz-font-base that will fallback to inherit
=> fix: badge font-family

src/cosmoz-tab-card.js, src/cosmoz-tab.js
Style changes for tab cards according to updates in Figma.
[AB#15229](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/15229/)
[Figma design ref](https://www.figma.com/design/QIZfvPg7UljN8SvVukWSnd/Header-fixes-Cosmoz?node-id=17-114)
Linked to: [frontend repo PR](https://github.com/Neovici/cosmoz-frontend/pull/7207)
=> fix: match new styling changes for tab cards

src/cosmoz-tab-card.js
Add CSS rules for heading 
BREAKING CHANGE: `cosmoz-tab-card` heading must be an attribute
[AB#17862](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/17862/)
=> feat: add css rules for heading

src/next/use-tabs.js
Makes sure badge is rendered in cosmoz-tabs-next
=> fix: make sure badge is rendered in cosmoz-tabs-next
