- cosmoz-tab-card.html
- demo/card.html
> cosmoz-tab-card demo

- .eslintrc.json
- .vscode/settings.json
> ESLint support ES6

- cosmoz-tab.js
- cosmoz-tabbable-behavior.html
- cosmoz-tabbed-behavior.html
> Improve docs

- .eslintignore
- .gitignore
- .travis.yml
- analysis.json
- bower.json
- index.html
- package.json
- polymer.json
- yarn.lock
Add variants and iron-component-page 3.x
> Hybrid 2.0 element

- analysis.json
- cosmoz-tabbable-behavior.html
- cosmoz-tabbed-behavior.html
- demo/tab.html
- test/.eslintrc.json
- test/basic.html
Add `tab-select` and `tab-first-select` events.
Add tests for events.
Add documentation for events.
Add demos
fixes #13
> tab-select and tab-first-select events

- analysis.json
- cosmoz-tab-card.js
- cosmoz-tab.html
- cosmoz-tab.js
- cosmoz-tabbable-behavior.html
- cosmoz-tabbed-behavior.html
- cosmoz-tabs.html
- cosmoz-tabs.js
- demo/index.html
- test/basic.html
- test/cards.html
- test/events.html
- test/index.html
- test/sizing.html
Handle explicit size
Add related demos
Add related documentation
Add test suite
can be reviewed
fixes #15
> Explicit size

- analysis.json
- bower.json
- cosmoz-tabs.js
- demo/index.html
> Select item from hash-param only when items are avaiable

- analysis.json
- bower.json
- cosmoz-tabbable-behavior.html
- cosmoz-tabs.js
- demo/index.html
- package.json
- test/basic.html
- test/fallback-selection.html
- test/index.html
- test/sizing.html
Fix fallback-selection being a String
fixes #18
> cosmoz-tabs fallbackSelection should be set to first item

- analysis.json
- cosmoz-tabbed-behavior.html
- cosmoz-tabs.js
- test/basic.html
Forward badge and heading properties
> Forward badge and heading properties

- .codeclimate.yml
- .eslintrc.json
- analysis.json
- cosmoz-tab.js
- cosmoz-tabs.js
- demo/card.html
- demo/index.html
- demo/tab.html
- package.json
- test/accordion.html
- test/basic.html
- test/fallback-selection.html
- test/hash.html
- test/sizing.html
- yarn.lock
Notify property changes for `hidden`, `disabled`, `heading`, `badge` from `cosmoz-tab`.
Set default for `attrForSelected` to `name`. 
fixes #23
> Notify property changes from cosmoz-tab

- .eslintrc.json
- analysis.json
- cosmoz-tab-card.js
- cosmoz-tab.js
- cosmoz-tabbable-behavior.html
- cosmoz-tabbed-behavior.html
- cosmoz-tabs.html
- cosmoz-tabs.js
- demo/helpers/router-template.html
- demo/index.html
- demo/router.html
- demo/tab.html
- package.json
- test/accordion.html
- test/basic.html
- test/cards.html
- test/events.html
- test/fallback-selection.html
- test/hash.html
- test/sizing.html
- yarn.lock
* Remove attrForHashParam
* Added cosmoz-page-router demo
* Serialize values when comparing changes
> Improve hash-param

- cosmoz-tabs.html
- cosmoz-tabs.js
preventDefault() if clicking on link inside paper-tab
fixes #32
> preventDefault() if clicking on link inside paper-tab

- analysis.json
- cosmoz-tabs.html
- cosmoz-tabs.js
- demo/index.html
- demo/router.html
- test/hash.html
Integrate cosmoz-page-location changes.
To be merged after Neovici/cosmoz-page-route#19
> Integrate cosmoz-page-location changes

- analysis.json
- cosmoz-tab.js
- cosmoz-tabs.html
- cosmoz-tabs.js
- test/basic.html
- test/index.html
- test/invalid.html
> Re-evalute URL params

- .codeclimate.yml
- .eslintignore
- .gitignore
- .travis.yml
- bower.json
- cosmoz-tab.js
- cosmoz-tabbable-behavior.html
- package.json
- wct.conf.json
- yarn.lock
fixes https://github.com/Neovici/cosmoz-tabs/issues/40
> Tests code coverage and code climate config v2

- cosmoz-tabbed-behavior.html
This pull request updates behavior documentation.
Want 2 approves on this.
> Behavior documentation

- cosmoz-tabbable-behavior.html
- cosmoz-tabbed-behavior.html
- test/basic.html
> expose isActive property

- .eslintrc.json
- bower.json
- cosmoz-tab.html
- cosmoz-tab.js
- cosmoz-tabbed-template-behavior.html
- cosmoz-tabs.js
- demo/index.html
- demo/tab.html
- test/basic.html
- test/cards.html
- test/events.html
- test/fallback-selection.html
- test/hash.html
- test/helpers/template-bind-test-helper.html
- test/index.html
- test/invalid.html
- test/sizing.html
- test/tabbed-template-behavior.html
- wct.conf.json
- yarn.lock
fixes #44
Test in cosmoz-frontend, example of use in one view: https://github.com/Neovici/cosmoz-frontend/pull/236
Implement tests for 'tabbed template behavior' data binding. Done.
> Cosmoz tabbed template behavior

- .travis.yml
- cosmoz-tabbable-behavior.html
- test/sizing.html
- wct.conf.json
Sizing tests were completely broken and didn't catched a bug we have that prevented firing any resize on `cosmoz-tab` elements in `_onIronSelect` to resize the currently visible tab.
> Fixes resize behavior and restores sizing tests

- .codeclimate.yml
this makes it easier to run codeclimate on local
> (dev) add exclude_patterns for codeclimate

- cosmoz-tab-card.js
- cosmoz-tab.js
- cosmoz-tabs.js
- demo/card.html
- demo/index.html
- demo/router.html
- demo/tab.html
- test/sizing.html
https://github.com/Neovici/cosmoz-frontend/issues/1314
> (patch) modulizer erroneously escaped `attr$=` to `attr\$=`

- cosmoz-tab.js
* fixes [#1435](https://github.com/Neovici/cosmoz-frontend/issues/1435)
> Remove overflow-y: auto on content div

- package-lock.json
- package.json
upgrade to cosmoz-page-router@^6.0.0
> feat: upgrade to cosmoz-page-router@^6.0.0

- package-lock.json
- package.json
Update deps and cleanup package.json
Force new release
> feat: improve release and update deps

- lib/use-tabs.js
- lib/utils.js
- test/cosmoz-tabs-slot.test.js
This collects nested slotted cosmoz-tab elements:
slot> slot> cosmoz-tab
> fix: collect cosmoz-tab element from nested slots

- lib/use-tab.js
Notifies `cosmoz-tabs` when `cosmoz-tab` icon changes
> fix(cosmoz-tab): notify cosmoz-tabs when tab icon changes

- cosmoz-tab-card.js
> fix: add heading part

- src/next/use-tabs.js
activate tab by name attribute
> fix(use-tabs): activate tab by name attribute

- src/next/use-tabs.js
Adds support for separate title and content in renderTabs.
> fix(use-tabs): add support for separate title and content

- package-lock.json
- package.json
- src/use-tabs.js
Update `@neovici/cosmoz-router`.
> feat: update @neovici/cosmoz-router

- package-lock.json
- package.json
- src/use-tab.js
- src/use-tabs.js
BREAKING CHANGE: Upgrade cosmoz-utils@5
> feat(deps): upgrade cosmoz-utils

- .gitignore
- src/cosmoz-tabs.js
[AB#8531](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/8531)
I've added slot for stats in the tab nav.
Screen record:
https://user-images.githubusercontent.com/48321438/201048388-25bcd8a5-dde4-43e3-922b-610cb4f084c0.mov
> feat(stats): add slot for stats in the tab nav

- .github/workflows/workflow.yml
- package-lock.json
- package.json
- src/next/use-tabs.js
Fix disabled typo & update deps.
> fix: disabled typo

- src/next/index.d.ts
- src/next/use-tabs.d.ts
- src/next/use-tabs.js
Add fallback support & type def for use-tabs.
> feat(next/use-tabs): add fallback support

- src/next/use-tabs.d.ts
> feat(next/use-tabs): adjust tabs definition

- src/next/use-tabs.d.ts
> feat(next/use-tabs): adjust type

- .github/workflows/storybook.yml
- .github/workflows/workflow.yml
- package-lock.json
- package.json
- src/cosmoz-tab-card.js
- src/cosmoz-tab.js
- src/cosmoz-tabs.js
- src/next/cosmoz-tab.js
- src/next/cosmoz-tabs.js
- src/next/use-tabs.js
- src/render.js
- src/use-tab.js
- src/use-tabs.js
- stories/cosmoz-tab-card.stories.js
- stories/cosmoz-tab.stories.js
- stories/cosmoz-tabs-next.stories.js
- stories/cosmoz-tabs.stories.js
- test/cosmoz-tab-card.test.js
- test/cosmoz-tabs-slot.test.js
BREAKING CHANGE: Update to @pionjs/pion
> feat: update to pion

- package-lock.json
- package.json
- src/next/use-tabs.js
Handle the `title` tab  property being a function.
> feat(next/use-tabs): handle function title

- src/next/use-tabs.d.ts
- src/next/use-tabs.js
Implement renderActivated helper.
> feat: implement renderActivated helper

- src/cosmoz-tab-card.js
> feat(cosmoz-tab-card): flex the .content

- src/next/use-tabs.d.ts
Correct type for disable -> disabled.
> fix(use-tabs): correct type

- .github/workflows/storybook.yml
Update the `.github/workflows/storybook.yml` file so that it uses the base `cfg` workflow
> feat: update `storybook` gitHub workflow

- src/next/use-tabs.d.ts
- src/next/use-tabs.js
Support the `className` property in `renderTabs`.
> feat(next/use-tabs): support className in renderTabs

- src/cosmoz-tab-card.js
- src/cosmoz-tab.js
Edit style changes for tab cards according to updates in Figma.
[AB#15229](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/15229/)
[Figma design ref](https://www.figma.com/design/QIZfvPg7UljN8SvVukWSnd/Header-fixes-Cosmoz?node-id=17-114)
Linked to: https://github.com/Neovici/cosmoz-frontend/pull/7207
> fix: edit new styling for tab cards

- src/cosmoz-tab-card.js
Changes due to invoices overview redesign
[AB#10463](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/10463/)
> fix: changes due to invoices overview redesign
